server:
  port: 31001
spring:
  application:
    name: T134511679.admin.mia
  # ???????
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: hologres
      datasource:
        hologres:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://29.118.24.171:80/cdm_gp_dev?currentSchema=public&ApplicationName=east
          username: TMPXNED5pB46Gk6G
          password: mHCu9zzA3guX5RM7UoEnt24unFf2cE
          druid:
            socket-timeout: 300000
            connect-timeout: 300000
            initial-size: 5 # ????????????????0
            max-active: 20 # ??????????8
            min-idle: 10 # ???????
            keep-alive: true
            max-wait: 60000 # ?????????????????
            time-between-eviction-runs-millis: 2000  # ????????????????????????????
            min-evictable-idle-time-millis: 600000  # ??????????????????????
            max-evictable-idle-time-millis: 900000  # ??????????????????????
            validation-query: select 1
            test-while-idle: true # ???true???????????????testOnBorrow?false??????????????????????????????????????true
            test-on-borrow: false # ????????validationQuery????????,???????,???true
            test-on-return: false # ????????validationQuery????????,???????,???true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    vfs-impl: com.baomidou.mybatisplus.autoconfigure.SpringBootVFS
    call-setters-on-nulls: true
big-model:
  url: http://p001-gp18aibsm-sit.group.cpic.com/chatgpt/chatgpt/funcChat/gptAnswer
  app-token: 816a9d849e9f40feb0396523a3f4c933


