server:
  port: 31001
  compression:
    enabled: true
    mime-types: application/javascript
jasypt:
  encryptor:
    # 盐值
    password: PBEWITHMD5ANDDES
    # 指定加密方式
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  application:
    name: T134511679.admin.mia
  # ???????
  web:
    resources:
      static-locations: classpath:static/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: custapp
    ##password: ENC(309Gm8K+bt+Ev9iSO1KKonHyctRyFi9t2IQbTSMxFMQ=)
    password: Ce_Sh1%Pa2s_obdb
    url: jdbc:mysql://29.24.18.13:16063/coredb_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    vfs-impl: com.baomidou.mybatisplus.autoconfigure.SpringBootVFS
    call-setters-on-nulls: true
big-model:
  url: http://p001-gp18aibsm-sit.group.cpic.com/chatgpt/chatgpt/funcChat/gptAnswer
  app-token: 816a9d849e9f40feb0396523a3f4c933
  72b-bck:
    url: http://api-gp18aibsm-sit.group.cpic.com/openAPI/route/gateway
    longAppToken: XLUCAUY3KIDAEFGDAWIJGEMJSKOYM8XA
    serviceId: Cpic.All.Service.Ai.chat.completions

sm4:
  key: "!QAZ2wsx#EDC4rfv"